version: '3.8'

services:
  # PostgreSQL with pgvector for learning memory storage
  postgres:
    image: pgvector/pgvector:pg16
    container_name: learning-agent-db
    environment:
      POSTGRES_USER: learning_agent
      POSTGRES_PASSWORD: learning_agent_pass
      POSTGRES_DB: learning_memories
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - learning-agent-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learning_agent"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LangGraph server for the learning agent
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: learning-agent-server
    ports:
      - "2024:2024"
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_TRACING=true
      - LANGSMITH_PROJECT=learning-agent
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - DATABASE_URL=postgresql://learning_agent:learning_agent_pass@postgres:5432/learning_memories
    volumes:
      - ./src:/app/src:ro
      - ./.agent:/app/.agent
    networks:
      - learning-agent-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2024/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Deep Agents UI
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: learning-agent-ui
    ports:
      - "10300:3000"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=http://localhost:2024
      - NEXT_PUBLIC_AGENT_ID=learning_agent
      - NEXT_PUBLIC_LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    depends_on:
      - server
    networks:
      - learning-agent-network

networks:
  learning-agent-network:
    driver: bridge

volumes:
  agent-data:
  postgres_data:
